spring.application.name=brownbag

spring.datasource.url=jdbc:mysql://localhost:3306/education
spring.datasource.username=edu
spring.datasource.password=edu

























































server.tomcat.threads.max=4


spring.threads.virtual.enabled=false


